spring.application.name=ativdade-3

# Aponta para o container Docker
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

# Desativa o broker embutido para forçar o uso do Docker
spring.activemq.pool.enabled=false
